export const GameEvents = {
  GAME_INIT: 'GAME_INIT',
  GAME_START: 'GAME_START',
  GAME_TICK: 'GAME_TICK',
  GAME_STOP: 'GAME_STOP',

  STATE_UPDATED: 'STATE_UPDATED',
  CONFIG_UPDATED: 'CONFIG_UPDATED',
  MESSAGES_UPDATED: 'MESSAGES_UPDATED',

  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_REMOVED: 'PLAYER_REMOVED',
  PLAYER_UPDATED: 'PLAYER_UPDATED',

  PLAYER_ELIMINATED: 'PLAYER_ELIMINATED',
  PLAYER_WIN: 'PLAYER_WIN',
  PLAYER_LOSE: 'PLAYER_LOSE',

  PLAYER_AUTH_UPDATED: 'PLAYER_AUTH_UPDATED',
  LEADERBOARD_UPDATED: 'LEADERBOARD_UPDATED',

  TAKE_ORDER: 'TAKE_ORDER',
  MAKE_MOVE: 'MAKE_MOVE'
} as const;

export type GameEventType = (typeof GameEvents)[keyof typeof GameEvents];
